* Limits and Continuity

** ex.1: Limit

lim f(x) = 4
x->3

lim f(x) = 4
x->3-

lim f(x) = 4
x->3+

- the limit of f of x as x approaches 3 is 4
- the limit as we approach from the left is 4
- the limit as we aproach from the right is 4

** ex.2: Right and Left

lim f(x) = -4
x->3-

lim f(x) = 1
x->3+

- the function is discontinuos at x = 3,
- we have 2 limits from right and left, but
- the limit at x->3 does not exist

- the value of a function is not the same as the limit of the function
- we predict the limit by approximating infinitly close to the value,
but the value may be undefined, and the function can still have a limit,
- but if the value is infinity, we are infinitly approximating infinity
and in this case the limit does not exist from that direction


** ex.3: Continuity

*** Over a point
f is continuos when x=a if and only if

lim f(x) = f(a) 
x->a

*** Over an interval

f is cont. over (a,b) if and only if
f is cont. over every point in that interval

f is cont. over [a,b] if and only if

lim f(x) = f(a) and lim f(x) = f(b)
x->a+               x->b-

** Properties of Limits

lim f(x) = L    lim g(x) = M
x->a            x->a

lim( f(x) + g(x) ) = L + M     | Sum
x-> a

lim ( f(x) - g(x) ) = L - M    |  
x->a

lim ( f(x) * g(x) ) = L * M    | Product
x->a

lim ( f(x) / g(x) ) = L / M    | Difference

lim f(g(x)) = lim f( lim g(a) )| Composition
x->a


** Limits by substitution, factoring and rationalizing

ex.4:

f(x) = x^2 + x - 6 / x - 2 = (x + 3)(x - 2) / (x - 2) = x + 3 , x != 2

f(x) { x + 3     , x != 2
     { undefined , x = 2

lim f(x) = ?
x->2

ex.5:

lim x + 1/ sqrt(x + 5) - 2 = ?    | 0/0 
x-> -1

g(x) = x + 1/ sqrt(x + 5) - 2 =

= (x + 1 / sqrt(x + 5) - 2) * (sqrt(x + 5) + 2 / sqrt(x + 5) + 2) =

= (x + 1)(sqrt(x + 5) + 2) / x + 5 - 4 = sqrt(x + 5) + 2 , x != -1  

f(x) = sqrt(x + 5) + 2
f(x) = g(x) for all x != 1

lim g(x) = 4
x-> -1


(a + b)(a - b) = a^2 - b^2


** Limits of trigonometric functions

ex.6:

lim sin(x) = ? = sin(π) = 0
x-> π

sin and cosn are defined for all real numbers and are continuos
over thier entire domain (tan and cot are also continuous), and
thier limit will be the value of the function at that point 


lim tan(x) = lim sin(x)/cos(x) = 0 / -1 = 0 
x-> π

lim cot(x) = lim cos(x)/sin(x) = 
x-> π

sin π = sin(π/2 + π/2) = cos π/2 = 0
sin(π) = 0
cos(0) = 1
cos(π) = -1
cos(π/2) = 0


Note: 0/0 is undetermined form -> the limit may still exist

** Trigonometry Review

*** Radians

Degrees seem to be historic artefact(coinsidance)
Radians are more rational(neutral, universal)

1 radian = 1 part of the circle with length equal to the radius
1 radian = 1 radius

How many radians in a 360deg(circle)?

c = 2πr
360 deg = c / r = 2πr / r = 2π radians
180 deg = π radians
1 deg   = π / 180
1 radian = 180 / π

*** Unit circle definitions of sin and cos

  Unit circle - a circle with radius 1

           (0,1)
           |  . (a,b) === (cos Theta, sin Theta)
           |. . b       
(-1,0) --------- (1,0)
           | a
           |
      (0,-1)

  We have a right angled triangle between the x and radius
  Theta is the angle between the x and radius

  soh cah toa - works well with triangles where the angle is
  less than 90 deg, but breaks on the circle

  sin Theta = Opposite/Hypotenuse = a / 1 = a

  cos Theta = Opposite/Hypotenuse = b / 1 = b

  The point (a,b) on the circle gives us the sin and cos of Theta
  
  tan = sin / cos
  cot = 1 / tan (adjacent / opposite)


